#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PYTHON_BIN="${PYTHON_BIN:-python3}"
INPUT_BACKEND="${INPUT_BACKEND:-gpio}"
LOG_LEVEL="${LOG_LEVEL:-INFO}"
UI_BACKEND="${UI_BACKEND:-screen}"

# camera prototype validated kmsdrm for current Waveshare HDMI setup.
export SDL_VIDEODRIVER="${SDL_VIDEODRIVER:-kmsdrm}"
export RECOGNIZER_SCREEN_WIDTH="${RECOGNIZER_SCREEN_WIDTH:-480}"
export RECOGNIZER_SCREEN_HEIGHT="${RECOGNIZER_SCREEN_HEIGHT:-800}"
export RECOGNIZER_SCREEN_FULLSCREEN="${RECOGNIZER_SCREEN_FULLSCREEN:-1}"
export RECOGNIZER_SCREEN_FILL="${RECOGNIZER_SCREEN_FILL:-1}"
export RECOGNIZER_UI_SCALE="${RECOGNIZER_UI_SCALE:-1.0}"
export RECOGNIZER_PREVIEW_ROTATION="${RECOGNIZER_PREVIEW_ROTATION:-0}"
export RECOGNIZER_CAMERA_WIDTH="${RECOGNIZER_CAMERA_WIDTH:-800}"
export RECOGNIZER_CAMERA_HEIGHT="${RECOGNIZER_CAMERA_HEIGHT:-480}"
export RECOGNIZER_CAMERA_ROTATION="${RECOGNIZER_CAMERA_ROTATION:-90}"
export RECOGNIZER_CAMERA_SWAP_RED_BLUE="${RECOGNIZER_CAMERA_SWAP_RED_BLUE:-1}"

exec "$PYTHON_BIN" app/main.py --runtime real --input "$INPUT_BACKEND" --ui-backend "$UI_BACKEND" --log-level "$LOG_LEVEL" "$@"
